#!/bin/sh
echo starting
export RAILS_ENV=production
cd /usr/lib/hs/cloudcontroller
exec 2>&1
exec setuidgid hscc stdbuf -o0 -e0 bin/rake periodictask:run_worker ................................................................................................................................................................
